import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { MessageProvider } from "@/contexts/messageProvider";
import { AuthProvider } from "@/contexts/authProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-black via-slate-950 to-slate-900">
        <AuthProvider>
          <MessageProvider>
            <Header />
              {children}
            <Footer />
          </MessageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
