import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { MessageProvider } from "@/contexts/messageProvider";
import { AuthProvider } from "@/contexts/authProvider";
import { ReactQueryProvider } from "@/contexts/reactQueryProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ReactQueryProvider>
          <AuthProvider>
            <MessageProvider>
              <Header />
                {children}
              <Footer />
            </MessageProvider>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
